config: !!python/object/new:easydict.EasyDict
  dictitems:
    IoU_space: 3
    batch_size: 1
    bc_channel: 9
    bc_weight: 1.0
    box_aware: true
    box_weight: 0.2
    category_name: Car
    cfg: cfgs/EXPL_BAT_Car.yaml
    check_val_every_n_epoch: 1
    checkpoint: null
    coordinate_mode: camera
    dataset: kitti
    degrees: true
    epoch: 60
    feature_channel: 256
    from_epoch: 0
    gpu: &id001
    - 0
    hidden_channel: 256
    k: 4
    limit_box: false
    log_dir: null
    lr: 0.001
    lr_decay_rate: 0.2
    lr_decay_step: 12
    model_bb_offset: 0
    model_bb_scale: 1.25
    net_model: EXPL_BAT
    normalize_xyz: false
    num_candidates: 4
    num_proposal: 64
    objectiveness_weight: 1.5
    optimizer: Adam
    out_channel: 256
    path: /home/xiayan/tracking/data/training
    preload_offset: 10
    preloading: true
    random_sample: false
    reference_BB: previous_result
    sample_per_epoch: -1
    save_top_k: -1
    search_bb_offset: 2
    search_bb_scale: 1.25
    search_size: 1024
    seg_weight: 0.2
    shape_aggregation: firstandprevious
    template_size: 512
    test: false
    up_axis: &id002
    - 0
    - 0
    - 1
    use_fps: true
    use_search_bc: false
    use_search_feature: false
    use_z: true
    vote_channel: 256
    vote_weight: 1.0
    wd: 0
    workers: 10
  state:
    IoU_space: 3
    batch_size: 1
    bc_channel: 9
    bc_weight: 1.0
    box_aware: true
    box_weight: 0.2
    category_name: Car
    cfg: cfgs/EXPL_BAT_Car.yaml
    check_val_every_n_epoch: 1
    checkpoint: null
    coordinate_mode: camera
    dataset: kitti
    degrees: true
    epoch: 60
    feature_channel: 256
    from_epoch: 0
    gpu: *id001
    hidden_channel: 256
    k: 4
    limit_box: false
    log_dir: null
    lr: 0.001
    lr_decay_rate: 0.2
    lr_decay_step: 12
    model_bb_offset: 0
    model_bb_scale: 1.25
    net_model: EXPL_BAT
    normalize_xyz: false
    num_candidates: 4
    num_proposal: 64
    objectiveness_weight: 1.5
    optimizer: Adam
    out_channel: 256
    path: /home/xiayan/tracking/data/training
    preload_offset: 10
    preloading: true
    random_sample: false
    reference_BB: previous_result
    sample_per_epoch: -1
    save_top_k: -1
    search_bb_offset: 2
    search_bb_scale: 1.25
    search_size: 1024
    seg_weight: 0.2
    shape_aggregation: firstandprevious
    template_size: 512
    test: false
    up_axis: *id002
    use_fps: true
    use_search_bc: false
    use_search_feature: false
    use_z: true
    vote_channel: 256
    vote_weight: 1.0
    wd: 0
    workers: 10
